/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
 *
 * Generated on: 04-Mar-2012 21:05:07
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 204
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <tmwtypes.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files (x86)\MATLAB\R2011a Student\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */

#define N 204

const int16_T h[204] = {
       -2,      1,     -1,      1,     -1,      1,     -2,      2,     -2,
        2,     -3,      3,     -3,      4,     -4,      5,     -5,      6,
       -7,      7,     -8,      9,    -10,     11,    -12,     13,    -14,
       15,    -16,     18,    -19,     21,    -23,     24,    -26,     28,
      -30,     33,    -35,     37,    -40,     43,    -46,     49,    -52,
       56,    -59,     63,    -67,     71,    -76,     81,    -86,     91,
      -96,    102,   -108,    114,   -121,    128,   -135,    142,   -150,
      159,   -168,    177,   -187,    198,   -209,    220,   -233,    246,
     -260,    274,   -290,    307,   -325,    344,   -365,    388,   -412,
      439,   -468,    500,   -535,    575,   -619,    668,   -725,    790,
     -866,    956,  -1064,   1197,  -1364,   1581,  -1877,   2302,  -2967,
     4163,  -6948,  20859,  20859,  -6948,   4163,  -2967,   2302,  -1877,
     1581,  -1364,   1197,  -1064,    956,   -866,    790,   -725,    668,
     -619,    575,   -535,    500,   -468,    439,   -412,    388,   -365,
      344,   -325,    307,   -290,    274,   -260,    246,   -233,    220,
     -209,    198,   -187,    177,   -168,    159,   -150,    142,   -135,
      128,   -121,    114,   -108,    102,    -96,     91,    -86,     81,
      -76,     71,    -67,     63,    -59,     56,    -52,     49,    -46,
       43,    -40,     37,    -35,     33,    -30,     28,    -26,     24,
      -23,     21,    -19,     18,    -16,     15,    -14,     13,    -12,
       11,    -10,      9,     -8,      7,     -7,      6,     -5,      5,
       -4,      4,     -3,      3,     -3,      2,     -2,      2,     -2,
        1,     -1,      1,     -1,      1,     -2
};
